version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CodeDeploy
    overwrite: yes
permissions:
  - object: /home/ubuntu/CodeDeploy
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
