name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Check Node v
        run: node -v

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: zip create
        run: zip -qq -r ./hoon-build.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./hoon-build.zip s3://hoon-server-s3-bucket/hoon-build.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name hoon-deploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name hoon-deploy-group
          --s3-location bucket=hoon-server-s3-bucket,bundleType=zip,key=hoon-build.zip
